version: 2.1
jobs:
  test:
    docker:
      - image: fabiogallotti/tutorial_ci
    steps:
      - checkout
      - run:
         name: Setup Code Climate test-reporter
         command: |
          # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Run tests
          command: |
           python -m pytest --cov-report xml --cov-report term --cov sample tests/test_sample.py
           python -m pytest --cov-report xml --cov-report term --cov Chat tests/test_chat.py
      - run:
          name: Send coverage to Code Climate
          command: |
            ./cc-test-reporter after-build --exit-code $? --debug
      - run:
          name: Send to codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -Z
workflows:
  test:
    jobs:
      - test
